CREATE TABLE IF NOT EXISTS Sections (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS SubSections (
  id SERIAL PRIMARY KEY,
  section_id INT NOT NULL REFERENCES Sections(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Files (
  id SERIAL PRIMARY KEY,
  subsection_id INT NOT NULL REFERENCES SubSections(id) ON DELETE CASCADE,
  file_type VARCHAR(50) NOT NULL,
  file_path TEXT NOT NULL UNIQUE
);
